server:
  port: 8000

spring:
  datasource:
    url: ${POSTGRE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update

jwt:
  key: ${JWT_SECRET}

transaction:
  tranfer_fail: "Transaction is invalid, please call a customer care.\n We are sorry for any inconvenience. \n Thank you for using WayaPayChat"
  transfer_successful: "::: Transaction successful :::"
